#!/bin/sh

ln -s maccess.c lien_symbolique01
ln -s lien_symbolique01 lien_symbolique02
ln -s lien_symbolique02 lien_symbolique03
ln -s lien_symbolique03 lien_symbolique04
ln -s lien_symbolique04 lien_symbolique05
ln -s lien_symbolique05 lien_symbolique06
ln -s lien_symbolique06 lien_symbolique07
ln -s lien_symbolique07 lien_symbolique08
ln -s lien_symbolique08 lien_symbolique09
ln -s lien_symbolique09 lien_symbolique10
ln -s lien_symbolique10 lien_symbolique11
ln -s lien_symbolique11 lien_symbolique12
ln -s lien_symbolique12 lien_symbolique13
ln -s lien_symbolique13 lien_symbolique14
ln -s lien_symbolique14 lien_symbolique15
ln -s lien_symbolique15 lien_symbolique16
ln -s lien_symbolique16 lien_symbolique17
ln -s lien_symbolique17 lien_symbolique18
ln -s lien_symbolique18 lien_symbolique19
ln -s lien_symbolique19 lien_symbolique20
ln -s lien_symbolique20 lien_symbolique21
ln -s lien_symbolique21 lien_symbolique22
ln -s lien_symbolique22 lien_symbolique23
ln -s lien_symbolique23 lien_symbolique24
ln -s lien_symbolique24 lien_symbolique25
ln -s lien_symbolique25 lien_symbolique26
ln -s lien_symbolique26 lien_symbolique27
ln -s lien_symbolique27 lien_symbolique28
ln -s lien_symbolique28 lien_symbolique29
ln -s lien_symbolique29 lien_symbolique30
ln -s lien_symbolique30 lien_symbolique31
ln -s lien_symbolique31 lien_symbolique32
ln -s lien_symbolique32 lien_symbolique33
ln -s lien_symbolique33 lien_symbolique34
ln -s lien_symbolique34 lien_symbolique35
ln -s lien_symbolique35 lien_symbolique36
ln -s lien_symbolique36 lien_symbolique37
ln -s lien_symbolique37 lien_symbolique38
ln -s lien_symbolique38 lien_symbolique39
ln -s lien_symbolique39 lien_symbolique40
ln -s lien_symbolique40 lien_symbolique41
ln -s lien_symbolique41 lien_symbolique42
ln -s lien_symbolique42 lien_symbolique43
ln -s lien_symbolique43 lien_symbolique44
